# -*- coding: utf-8 -*-
"""image2gif.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1F-SWqKZvdTSX01sKKFBPL3lWK5A5fT4y
"""

from google.colab import drive
drive.mount('/content/drive')

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/drive/MyDrive/DL_Final/
!ls

import cv2
import os
import imageio

def frames_to_video(input_folder, output_gif, output_mp4, fps):
    img_files = sorted([f for f in os.listdir(input_folder) if os.path.isfile(os.path.join(input_folder, f))])

    if not img_files:
        print(f"No image files found in {input_folder}")
        return

    first_img = cv2.imread(os.path.join(input_folder, img_files[0]))

    if first_img is None:
        print(f"Cannot read image {os.path.join(input_folder, img_files[0])}")
        return

    height, width, layers = first_img.shape
    size = (width, height)

    fourcc = cv2.VideoWriter_fourcc(*'mp4v')
    video_writer = cv2.VideoWriter(output_mp4, fourcc, fps, size)

    gif_writer = imageio.get_writer(output_gif, mode='I', fps=fps)

    for img_file in img_files:
        img_path = os.path.join(input_folder, img_file)
        frame = cv2.imread(img_path)
        
        if frame is None:
            print(f"Cannot read image {img_path}")
            continue

        video_writer.write(frame)
        gif_writer.append_data(cv2.cvtColor(frame, cv2.COLOR_BGR2RGB))

    video_writer.release()
    gif_writer.close()

if __name__ == "__main__":
    input_folder = '/content/drive/MyDrive/DL_Final/bun/'
    output_gif = '/content/drive/MyDrive/DL_Final/output/pixl.gif'
    output_mp4 = '/content/drive/MyDrive/DL_Final/output/pixl.mp4'
    fps = 30

    frames_to_video(input_folder, output_gif, output_mp4, fps)